spring:
  application:
    name: opencarwash
  security:
    jwt:
      expirationAccessMs: 3600000
      expirationRefreshMs: 2952000000
      secret: secret
server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/opencarwash
    driverClassName: org.postgresql.Driver
    username:
    password:

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

---

spring:
  profiles:
    active:
      test